services:
  redis:
    image: redis:latest
    command: redis-server
    restart: always
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "8081:8081"
    networks:
      - redis-network
    depends_on:
      - redis

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      LANG: pt_BR.utf-8
      POSTGRES_USER: lpzt
      POSTGRES_PASSWORD: "@@paz123"
      POSTGRES_DB: contacorrente
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - redis-network

volumes:
  redis:
  redis-config:
  db:

networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24